CREATE TABLE squads
(
  id SERIAL PRIMARY KEY UNIQUE,
  user_id varchar NOT NULL
);

CREATE TABLE firstTeam
(
  id SERIAL PRIMARY KEY UNIQUE,
  position VARCHAR,
  position_order INT,
    FOREIGN KEY (squad_id) REFERENCES squads(id) ON UPDATE CASCADE,
  FOREIGN KEY (player_id) REFERENCES FIFA23(id) ON UPDATE CASCADE
);

CREATE TABLE substitutes
(
  PRIMARY KEY (id) UNIQUE,
  FOREIGN KEY (squad_id) REFERENCES squad(id) ON UPDATE CASCADE,
  position varchar,
  FOREIGN KEY (player_id) REFERENCES FIFA23(id) ON UPDATE CASCADE,
);

CREATE TABLE substitutes
(
  PRIMARY KEY (id) UNIQUE,
  FOREIGN KEY (squad_id) REFERENCES squad(id) ON UPDATE CASCADE,
  FOREIGN KEY (player_id) REFERENCES FIFA23(id) ON UPDATE CASCADE,
);